# This file was generated by GoReleaser. DO NOT EDIT.
cask "dew" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "73d4c36a92b8ceb9563419c276ad5ea1948cec7dc9e31981a1572c7df0076090"
      url "https://github.com/vedanta/dew/releases/download/v#{version}/dew_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "39555cdbbf606d1b10c9c9138b63b1578842061b6748653789654d6e86eea429"
      url "https://github.com/vedanta/dew/releases/download/v#{version}/dew_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "23aa383a0993e1d235cbf508ca33cd3664df54f1004bb6eff6918c4bb127a717"
      url "https://github.com/vedanta/dew/releases/download/v#{version}/dew_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "731313a6f7e31388d716a2605d4d55835514f9a982dad38649a011259b5d4cd6"
      url "https://github.com/vedanta/dew/releases/download/v#{version}/dew_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dew"
  desc "Manage the private local files Git intentionally ignores"
  homepage "https://github.com/vedanta/dew"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dew"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dew"]
    end
  end

  # No zap stanza required

end
