# This file was generated by GoReleaser. DO NOT EDIT.
cask "dew" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "c44fdd9990f6b1121e995873d9324bc9ac8a78cdf611cc2856c489d2f0febb36"
      url "https://github.com/vedanta/dew/releases/download/v#{version}/dew_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d7d4e336c2bb7cafaa56fe30d2d90e9752d19e0da70be94122ef4f8f4b910961"
      url "https://github.com/vedanta/dew/releases/download/v#{version}/dew_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bde2e5ec57669fc8e44266eefddc2bab047696ce8f78c9f3f4aef6900bd2825a"
      url "https://github.com/vedanta/dew/releases/download/v#{version}/dew_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a9e596fb757537086a57d669feeaad94cb0dbb1e37534ba105fe75cbca3692fc"
      url "https://github.com/vedanta/dew/releases/download/v#{version}/dew_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dew"
  desc "Manage the private local files Git intentionally ignores"
  homepage "https://github.com/vedanta/dew"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dew"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dew"]
    end
  end

  # No zap stanza required

end
