# This file was generated by GoReleaser. DO NOT EDIT.
cask "dew" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "c756c4dfb1b63304dcec16dab001b2bb895f7823be93f3656c644a2b9f626c29"
      url "https://github.com/vedanta/dew/releases/download/v#{version}/dew_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9056698955bbe8801a6c8bd5e414287f21f465dce6ae1bf7859b952d9bf8ce97"
      url "https://github.com/vedanta/dew/releases/download/v#{version}/dew_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "38fe0461ef4cfeca9cef7f174e589cc099185e9e190af4b521e35f5bdbfaa897"
      url "https://github.com/vedanta/dew/releases/download/v#{version}/dew_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "354e3c590ee8728b8ceacdcc1d00ba77a6a9c64c2f34d6cc5845296d66ac76d2"
      url "https://github.com/vedanta/dew/releases/download/v#{version}/dew_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dew"
  desc "Manage the private local files Git intentionally ignores"
  homepage "https://github.com/vedanta/dew"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dew"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dew"]
    end
  end

  # No zap stanza required

end
